<a href="https://colab.research.google.com/github/Technight27/Python-Codes/blob/main/Aug_23_ML_Day_2_Python_Operators_Conditions_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a  =50.6
print (a)
print  (type (a))

50.6
<class 'float'>


In [ ]:
a  =50
print (a)
print  (type (a))

50
<class 'int'>


In [ ]:
a  =50.6
print (a)
print  (type (a))

50.6
<class 'float'>


In [ ]:
a  ='Sunday'
print (a)
print  (type (a))

Sunday
<class 'str'>


In [ ]:
a  =True
print (a)
print  (type (a))

True
<class 'bool'>


In [ ]:
a = False
print (a)
print  (type (a))

False
<class 'bool'>


In [ ]:
a = 5+10J
print (a)
print (type (a))

(5+10j)
<class 'complex'>


In [ ]:
b= 5+10J
print (b)
print (type (b))

(5+10j)
<class 'complex'>


In [ ]:
a+b

(10+20j)

In [ ]:
marks = [65,78,55,48]
marks

[65, 78, 55, 48]

In [ ]:
marks [1]

78

In [ ]:
marks [-3]

78

In [ ]:
marks = [65,78,55,48]
marks

[65, 78, 55, 48]

In [ ]:
marks = [65,78,55,48, 4.5, True , [20,21,22]]
print (marks)

[65, 78, 55, 48, 4.5, True, [20, 21, 22]]


In [ ]:
List  =  []
Tuple =()

In [ ]:
l1 = [10,20,30,30,40]
print (l1)
print (type (l1))

[10, 20, 30, 30, 40]
<class 'list'>


In [ ]:
t1 = (10,20,30,30,40)
print (t1)
print (type (t1))

(10, 20, 30, 30, 40)
<class 'tuple'>


In [ ]:
l1

[10, 20, 30, 30, 40]

In [ ]:
l1[2] =35
print (l1)

[10, 20, 35, 30, 40]


In [ ]:
t1

(10, 20, 30, 30, 40)

In [ ]:
t1[2]

30

In [ ]:
t1[2] =35

TypeError: 'tuple' object does not support item assignment

In [ ]:
l1

[10, 20, 35, 30, 40]

In [ ]:
l1.append (35)
l1

[10, 20, 35, 30, 40, 35]

In [ ]:
t1

(10, 20, 30, 30, 40)

In [ ]:
t1.append (35)

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
range (20,30,2)

range(20, 30, 2)

In [ ]:
import numpy as np
np.arange (20,30,2)

array([20, 22, 24, 26, 28])

In [ ]:
np.arange (10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange (10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
for i in range (5):
    print (i)

0
1
2
3
4


In [ ]:
for i in range (20):
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
for i in range (15,20):
    print (i)

15
16
17
18
19


In [ ]:
for i in range (10,100,10):
    print (i)

10
20
30
40
50
60
70
80
90


In [ ]:
for i in range (50,-50,-10):
    print (i)

50
40
30
20
10
0
-10
-20
-30
-40


In [ ]:
for i in range (50,-51,-10):
    print (i)

50
40
30
20
10
0
-10
-20
-30
-40
-50


In [ ]:
for i in range (1,10):
    print (i)

1
2
3
4
5
6
7
8
9


In [ ]:
student = {'Roll No': 100, 'Name':'Sam'}
print (student)
print (type (student))

{'Roll No': 100, 'Name': 'Sam'}
<class 'dict'>


In [ ]:
student['Roll No']

100

In [ ]:
student['Name']

'Sam'

In [ ]:
student = {'Roll No': [100,101,102] ,'Name':['Sam','Ann']}
print (student)
print (type (student))

{'Roll No': [100, 101, 102], 'Name': ['Sam', 'Ann']}
<class 'dict'>


In [ ]:
student ['Roll No']

[100, 101, 102]

In [ ]:
student ['Roll No'][1]

101

In [ ]:
List  = []
Tuple = ()
Set = {}
Dict = {'Key': 'Value'}

In [ ]:
s1 = {10,20,30,20,30}
print (s1)

{10, 20, 30}


In [ ]:

print (s1)
s1.add (40)
print (s1)

{10, 20, 30}
{40, 10, 20, 30}


In [ ]:
fs1 = frozenset ({10,20,30,20,30})
print (type (fs1))
print (fs1)

<class 'frozenset'>
frozenset({10, 20, 30})


In [ ]:
fs1.add (40)

AttributeError: 'frozenset' object has no attribute 'add'

In [ ]:
True

True

In [ ]:
False

False

In [ ]:
a = 50.6
print (type (a))

<class 'float'>


In [ ]:
a = 50.6
print (type (a))
int (a)

<class 'float'>


50

In [ ]:
a = 50.6
print (type (a))
str (a)

<class 'float'>


'50.6'

In [ ]:
l1 = [10,20,30]
tuple (l1)

(10, 20, 30)

In [ ]:
# 0 will be False
# Non Zero will be True

In [ ]:
bool (0)

False

In [ ]:
bool (56112)

True

In [ ]:
bool (0.0000000000001)

True

In [ ]:
int (False)

0

In [ ]:
int (True)

1

In [ ]:
x = str (False)
print (x)
print (type (x))

False
<class 'str'>


In [ ]:
l1

[10, 20, 30]

In [ ]:
l1 = [10,20,30,20,30]
set(l1)

{10, 20, 30}

In [ ]:
frozenset(l1)

frozenset({10, 20, 30})

In [ ]:
b1 = True
str (b1)

'True'

In [ ]:
m = bool ('True')
print (type (m))

<class 'bool'>


In [ ]:
m = bool ('Sunday')
print (type (m))
print (m)

<class 'bool'>
True


In [ ]:
a = 50
b = 20
c = a+b
print (c)

70


In [ ]:
a = 50
b = 20
c = a-b
print (c)

30


In [ ]:
a = 50
b = 20
c = a*b
print (c)

1000


In [ ]:
a = 50
b = 20
c = a/b
print (c)

2.5


In [ ]:
a = 50
b = 20
c = a %b
print (c)

10


In [ ]:
a = 50
b = 20
c = a //b
print (c)

2


In [ ]:
a = 46
b =8
c = a %b
print (c)

6


In [ ]:
a = 46
b =8
c = a //b
print (c)

5


In [ ]:
a = 46
b =8
c = a /b
print (c)

5.75


In [ ]:
5 ** 3

125

In [ ]:
5 *5*5

125

In [ ]:
2 * 2*2*2 * 2*2*2*2*2*2

1024

In [ ]:
2 **10

1024

In [ ]:
a = 46
b =8
c = a **b
print (c)


20047612231936


In [ ]:
46 *46 *46 *46 *46 *46 *46 *46

20047612231936

In [ ]:
a = 50
b = 20
a= a+b
print (a)

70


In [ ]:
a = 50
b = 20
a +=b
print (a)

70


In [ ]:
a = 50
b = 20
b+=a  # b = b+a
print (b)

70


In [ ]:
a = 50
b = 20
a -=b
print (a)

30


In [ ]:
'''
a = 50
b = 20
b+=a  # b = b+a
print (b)
'''
print (a)

30


In [ ]:
a = 50
b = 20
a *=b
print (a)

1000


In [ ]:
a = 50
b = 20
a /=b
print (a)

2.5


In [ ]:
a = 50
b = 20
b/=a
print (b)

0.4


In [ ]:
a = 50
b = 20
a %=b
print (a)

10


In [ ]:
a = 50
b = 20
a //=b
print (a)

2


In [ ]:
a = 50
b = 20
a **=b
print (a)

9536743164062500000000000000000000


In [ ]:
a = 100
b = 200
print ( a >b)

False


In [ ]:
a = 100
b = 200
print ( a <b)

True


In [ ]:
a = 200
b = 200
print ( a <b)

False


In [ ]:
a = 200
b = 200
print ( a <=b)

True


In [ ]:
a = 200
b = 200
print ( a ==b)

True


In [ ]:
a = 200
b = 200
print ( a !=b)

False


In [ ]:
from math import pi
r = float(input ("Input the radius of the circle : "))
print ("The area of the circle with radius " + str(r) + " is: " + str(pi * r**2))


Input the radius of the circle : 5
The area of the circle with radius 5.0 is: 78.53981633974483


In [ ]:
3.1415

In [ ]:
import sys
print("Python version")
print (sys.version)
print("Version info.")
print (sys.version_info)


Python version
3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)]
Version info.
sys.version_info(major=3, minor=9, micro=15, releaselevel='final', serial=0)


In [ ]:
dir (sys)

['__breakpointhook__',
 '__displayhook__',
 '__doc__',
 '__excepthook__',
 '__interactivehook__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__stderr__',
 '__stdin__',
 '__stdout__',
 '__unraisablehook__',
 '_base_executable',
 '_clear_type_cache',
 '_current_frames',
 '_debugmallocstats',
 '_enablelegacywindowsfsencoding',
 '_framework',
 '_getframe',
 '_git',
 '_home',
 '_xoptions',
 'addaudithook',
 'api_version',
 'argv',
 'audit',
 'base_exec_prefix',
 'base_prefix',
 'breakpointhook',
 'builtin_module_names',
 'byteorder',
 'call_tracing',
 'copyright',
 'displayhook',
 'dllhandle',
 'dont_write_bytecode',
 'exc_info',
 'excepthook',
 'exec_prefix',
 'executable',
 'exit',
 'flags',
 'float_info',
 'float_repr_style',
 'get_asyncgen_hooks',
 'get_coroutine_origin_tracking_depth',
 'get_int_max_str_digits',
 'getallocatedblocks',
 'getdefaultencoding',
 'getfilesystemencodeerrors',
 'getfilesystemencoding',
 'getprofile',
 'getrecursionlimit',
 'getrefcount',
 'get