<a href="https://colab.research.google.com/github/Technight27/Python-Codes-Data-Science/blob/main/Aug_23_DS_Day_9_Data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


In [ ]:
os.getcwd()

'C:\\Users\\noble'

In [ ]:
os.chdir ('C:\\Noble\\Training\\Acmegrade\\Data Science\\19 Aug 2023\\Aug 23 DS Day9\\')

In [ ]:
df1= pd.read_excel('Data Preprocessing Data File.xlsx')
df1

Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes

In [ ]:
x = df1.iloc[:,:-1]
x

Country   Age   Salary 
0   France   44.0  72000.0
1       NaN  27.0  48000.0
2  Germany    NaN  54000.0
3    Spain   39.0      NaN
4  Germany    NaN  64000.0
5   France   35.0  58000.0
6    Spain   39.0  52000.0
7   France   48.0      NaN
8  Germany   50.0  83000.0
9   France   37.0  67000.0

In [ ]:
x = df1.iloc[:,:-1].values
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [ ]:
import sklearn.impute as im
si = im.SimpleImputer()

In [ ]:
x[:,0]

array(['France ', nan, 'Germany ', 'Spain ', 'Germany ', 'France ',
       'Spain ', 'France ', 'Germany ', 'France '], dtype=object)

In [ ]:
x[:,0:1]

array([['France '],
       [nan],
       ['Germany '],
       ['Spain '],
       ['Germany '],
       ['France '],
       ['Spain '],
       ['France '],
       ['Germany '],
       ['France ']], dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy ='most_frequent')
si.fit_transform (x[:,0:1])

array([['France '],
       ['France '],
       ['Germany '],
       ['Spain '],
       ['Germany '],
       ['France '],
       ['Spain '],
       ['France '],
       ['Germany '],
       ['France ']], dtype=object)

In [ ]:
help (si)

Help on SimpleImputer in module sklearn.impute._base object:

class SimpleImputer(_BaseImputer)
 |  SimpleImputer(*, missing_values=nan, strategy='mean', fill_value=None, verbose=0, copy=True, add_indicator=False)
 |  
 |  Imputation transformer for completing missing values.
 |  
 |  Read more in the :ref:`User Guide <impute>`.
 |  
 |  .. versionadded:: 0.20
 |     `SimpleImputer` replaces the previous `sklearn.preprocessing.Imputer`
 |     estimator which is now removed.
 |  
 |  Parameters
 |  ----------
 |  missing_values : int, float, str, np.nan or None, default=np.nan
 |      The placeholder for the missing values. All occurrences of
 |      `missing_values` will be imputed. For pandas' dataframes with
 |      nullable integer dtypes with missing values, `missing_values`
 |      should be set to `np.nan`, since `pd.NA` will be converted to `np.nan`.
 |  
 |  strategy : str, default='mean'
 |      The imputation strategy.
 |  
 |      - If "mean", then replace missing values usi

In [ ]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy ='most_frequent')
x[:,0:1] = si.fit_transform (x[:,0:1])
print (x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' nan 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' nan 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [ ]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy ='mean')
x[:,1:2] = si.fit_transform (x[:,1:2])
print (x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' 39.875 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' 39.875 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [ ]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
x[:,2:] = si.fit_transform (x[:,2:])
print (x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' 39.875 54000.0]
 ['Spain ' 39.0 62250.0]
 ['Germany ' 39.875 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 62250.0]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [ ]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
x[:,2:] = si.fit_transform (x[:,2:])
print (x)

In [ ]:
x[:,0]

array(['France ', 'France ', 'Germany ', 'Spain ', 'Germany ', 'France ',
       'Spain ', 'France ', 'Germany ', 'France '], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,0] =le.fit_transform (x[:,0])
x

array([[0, 44.0, 72000.0],
       [0, 27.0, 48000.0],
       [1, 39.875, 54000.0],
       [2, 39.0, 62250.0],
       [1, 39.875, 64000.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 62250.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [ ]:
help(ColumnTransformer)

Help on class ColumnTransformer in module sklearn.compose._column_transformer:

class ColumnTransformer(sklearn.base.TransformerMixin, sklearn.utils.metaestimators._BaseComposition)
 |  ColumnTransformer(transformers, *, remainder='drop', sparse_threshold=0.3, n_jobs=None, transformer_weights=None, verbose=False, verbose_feature_names_out=True)
 |  
 |  Applies transformers to columns of an array or pandas DataFrame.
 |  
 |  This estimator allows different columns or column subsets of the input
 |  to be transformed separately and the features generated by each transformer
 |  will be concatenated to form a single feature space.
 |  This is useful for heterogeneous or columnar data, to combine several
 |  feature extraction mechanisms or transformations into a single transformer.
 |  
 |  Read more in the :ref:`User Guide <column_transformer>`.
 |  
 |  .. versionadded:: 0.20
 |  
 |  Parameters
 |  ----------
 |  transformers : list of tuples
 |      List of (name, transformer, colum

In [ ]:
 Parameters
 |  ----------
 |  transformers : list of tuples
 |      List of (name, transformer, columns) tuples specifying the
 |      transformer objects to be applied to subsets of the data.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct =  ColumnTransformer(transformers =[('one hot', OneHotEncoder(),[0])],remainder = 'passthrough')
ct.fit_transform(x)

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 39.875, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 39.875, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
x

array([[0, 44.0, 72000.0],
       [0, 27.0, 48000.0],
       [1, 39.875, 54000.0],
       [2, 39.0, 62250.0],
       [1, 39.875, 64000.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 62250.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct =  ColumnTransformer(transformers =[('one hot', OneHotEncoder(),[0])],remainder = 'passthrough')
x= ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 39.875, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 39.875, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
y = df1.iloc [:,3]
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased , dtype: object

In [ ]:
y = df1.iloc [:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
yle = LabelEncoder()
y=yle.fit_transform (y)
y


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 39.875, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 39.875, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler
std_sca= StandardScaler()
x_STD = std_sca.fit_transform(x)
print (pd.DataFrame(x_STD))


     0         1    2         3         4
0  1.0 -0.654654 -0.5  0.664912  1.002707
1  1.0 -0.654654 -0.5 -2.075331 -1.465494
2 -1.0  1.527525 -0.5  0.000000 -0.848444
3 -1.0 -0.654654  2.0 -0.141042  0.000000
4 -1.0  1.527525 -0.5  0.000000  0.179973
5  1.0 -0.654654 -0.5 -0.785805 -0.437077
6 -1.0 -0.654654  2.0 -0.141042 -1.054127
7  1.0 -0.654654 -0.5  1.309675  0.000000
8 -1.0  1.527525 -0.5  1.632056  2.133965
9  1.0 -0.654654 -0.5 -0.463423  0.488498


In [ ]:
from sklearn.preprocessing import MinMaxScaler
Nm_x= MinMaxScaler()
x_NOR = Nm_x.fit_transform(x)
print (pd.DataFrame(x_NOR))


     0    1    2         3         4
0  1.0  0.0  0.0  0.739130  0.685714
1  1.0  0.0  0.0  0.000000  0.000000
2  0.0  1.0  0.0  0.559783  0.171429
3  0.0  0.0  1.0  0.521739  0.407143
4  0.0  1.0  0.0  0.559783  0.457143
5  1.0  0.0  0.0  0.347826  0.285714
6  0.0  0.0  1.0  0.521739  0.114286
7  1.0  0.0  0.0  0.913043  0.407143
8  0.0  1.0  0.0  1.000000  1.000000
9  1.0  0.0  0.0  0.434783  0.542857


In [ ]:
from sklearn.preprocessing import Normalizer
Nm_x= Normalizer()
x_NOR = Nm_x.fit_transform(x)
print (pd.DataFrame(x_NOR))


          0         1         2         3    4
0  0.000014  0.000000  0.000000  0.000611  1.0
1  0.000021  0.000000  0.000000  0.000562  1.0
2  0.000000  0.000019  0.000000  0.000738  1.0
3  0.000000  0.000000  0.000016  0.000627  1.0
4  0.000000  0.000016  0.000000  0.000623  1.0
5  0.000017  0.000000  0.000000  0.000603  1.0
6  0.000000  0.000000  0.000019  0.000750  1.0
7  0.000016  0.000000  0.000000  0.000771  1.0
8  0.000000  0.000012  0.000000  0.000602  1.0
9  0.000015  0.000000  0.000000  0.000552  1.0
