<a href="https://colab.research.google.com/github/Technight27/Python-Codes-Data-Science/blob/main/Aug_23_DS_Day_6_Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1= np.arange (100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
import numpy as np
arr1= np.arange (100,200)
arr1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [ ]:
print (arr1[10:],'\n')

[110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199] 



In [ ]:
print (arr1[:20],'\n')

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119] 



In [ ]:
print (arr1[10:20],'\n')

[110 111 112 113 114 115 116 117 118 119] 



In [ ]:
print (arr1[10:50:5])

[110 115 120 125 130 135 140 145]


In [ ]:
print (arr1[::10])

[100 110 120 130 140 150 160 170 180 190]


In [ ]:
arr_slice = slice (1,10,2)
print (arr_slice)


slice(1, 10, 2)


In [ ]:
print (arr1[::-5])

[199 194 189 184 179 174 169 164 159 154 149 144 139 134 129 124 119 114
 109 104]


In [ ]:
arr1 =  np.arange(9)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr1=arr1.reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
'''
4  5
7  8
'''
arr1[1:,1:]

array([[4, 5],
       [7, 8]])

In [ ]:
arr2 = arr1[0:2,0:2]
print (arr2)


[[0 1]
 [3 4]]


In [ ]:

print (arr1)
print (arr1.shape)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [ ]:
print (arr1.ndim)
print (arr1.itemsize)


2
4


In [ ]:
print (arr1.dtype)

int32


In [ ]:
print (arr1.size)

9


In [ ]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
print (arr1.min())

0


In [ ]:
print (arr1.max())

8


In [ ]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
print (arr1.sum())

36


In [ ]:
print (np.sqrt(arr1))

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


In [ ]:
print (np.std(arr1))

2.581988897471611


In [ ]:
dir (np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [ ]:
arr5 = np.empty([3,2], dtype =  float)
print (arr5)


[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
arr5 = np.empty([3,2], dtype =  int)
print (arr5)


[[-1698060240         624]
 [          0           0]
 [     131074 -2147483648]]


In [ ]:
arr5 = np.empty([3,2], dtype =  bool)
print (arr5)


[[False False]
 [False False]
 [False False]]


In [ ]:
arr5 = np.empty([3,2], dtype =  str)
print (arr5)


[['' '']
 ['' '']
 ['' '']]


In [ ]:
import numpy
for name in dir(numpy):
    print (name, end = '\t')


ALLOW_THREADS	AxisError	BUFSIZE	CLIP	ComplexWarning	DataSource	ERR_CALL	ERR_DEFAULT	ERR_IGNORE	ERR_LOG	ERR_PRINT	ERR_RAISE	ERR_WARN	FLOATING_POINT_SUPPORT	FPE_DIVIDEBYZERO	FPE_INVALID	FPE_OVERFLOW	FPE_UNDERFLOW	False_	Inf	Infinity	MAXDIMS	MAY_SHARE_BOUNDS	MAY_SHARE_EXACT	ModuleDeprecationWarning	NAN	NINF	NZERO	NaN	PINF	PZERO	RAISE	RankWarning	SHIFT_DIVIDEBYZERO	SHIFT_INVALID	SHIFT_OVERFLOW	SHIFT_UNDERFLOW	ScalarType	Tester	TooHardError	True_	UFUNC_BUFSIZE_DEFAULT	UFUNC_PYVALS_NAME	VisibleDeprecationWarning	WRAP	_CopyMode	_NoValue	_UFUNC_API	__NUMPY_SETUP__	__all__	__builtins__	__cached__	__config__	__deprecated_attrs__	__dir__	__doc__	__expired_functions__	__file__	__getattr__	__git_version__	__loader__	__name__	__package__	__path__	__spec__	__version__	_add_newdoc_ufunc	_distributor_init	_financial_names	_from_dlpack	_globals	_mat	_pytesttester	_version	abs	absolute	add	add_docstring	add_newdoc	add_newdoc_ufunc	alen	all	allclose	alltrue	amax	amin	angle	any	append	apply_along_axis	appl

In [ ]:
list1= [10,20,30]
arr1=  np.array(list1)
arr11= np.array(arr1)
arr11[1] =100
print (list1)
print (arr1)
print (arr11)


[10, 20, 30]
[10 20 30]
[ 10 100  30]


In [ ]:
list2 =[50,60,70]
arr2=  np.asarray(list2)
arr21= np.asarray(arr2)
arr21[1] =100
print (list2)
print (arr2)
print (arr21)



[50, 60, 70]
[ 50 100  70]
[ 50 100  70]


In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [ ]:
arr1 = np.array([1, 2, 3], dtype=bool)
arr1

array([ True,  True,  True])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print (arr)
print (arr.dtype)


[1 2 3 4 5]
int32


In [ ]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [ ]:

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


[0 1 2 3]


In [ ]:

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))


['apple' 'banana' 'cherry']


In [ ]:

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr)[::-1])


['cherry' 'banana' 'apple']


In [ ]:

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))



[[2 3 4]
 [0 1 5]]


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print (arr)


[[3 2 4]
 [5 0 1]]


In [ ]:
arr

array([[3, 2, 4],
       [5, 0, 1]])

In [ ]:
print (np.sort(arr, axis = 0))


[[3 0 1]
 [5 2 4]]


In [ ]:
print (np.sort(arr, axis = 1))


[[2 3 4]
 [0 1 5]]


In [ ]:
print (np.sort(arr, axis = 3))

AxisError: axis 3 is out of bounds for array of dimension 2

In [ ]:
import numpy as np
arr= np.arange(10,19)
print (arr)


[10 11 12 13 14 15 16 17 18]


In [ ]:
arr= np.delete (arr, 2)
print (arr)


[10 11 13 14 15 16 17 18]


In [ ]:
arr= np.arange(10,19)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:

arr= np.arange(10,19)
arr= np.delete (arr, [2,5])
print (arr)


[10 11 13 14 16 17 18]


In [ ]:

arr= np.arange(10,19)
print (arr)
arr= np.delete (arr, [2,5,8])
print (arr)

[10 11 12 13 14 15 16 17 18]
[10 11 13 14 16 17]


In [ ]:

arr= np.arange(10,22)
arr2 = arr.reshape(3,4)
arr2


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
a= np.delete (arr2,1,0)
a


array([[10, 11, 12, 13],
       [18, 19, 20, 21]])

In [ ]:
a= np.delete (arr2,1,1)
a

array([[10, 12, 13],
       [14, 16, 17],
       [18, 20, 21]])

In [ ]:
arr2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
a= np.delete (arr2,2,1)
a

array([[10, 11, 13],
       [14, 15, 17],
       [18, 19, 21]])

In [ ]:
a= np.delete (arr2,2,0)
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
arr2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
np.delete (arr2,1,0)

array([[10, 11, 12, 13],
       [18, 19, 20, 21]])

In [ ]:
np.delete (arr2,0,1)

array([[11, 12, 13],
       [15, 16, 17],
       [19, 20, 21]])