<a href="https://colab.research.google.com/github/Technight27/Python-Codes/blob/main/Aug_23_DS_Day_5_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.array ([])

array([], dtype=float64)

In [ ]:
np.array ([10,20,30])

array([10, 20, 30])

In [ ]:
l1 =  [ 10,20,30,'Sat', True]
l1

[10, 20, 30, 'Sat', True]

In [ ]:
np.array ([10,20,30,'Sat', True])

array(['10', '20', '30', 'Sat', 'True'], dtype='<U11')

In [ ]:
l1 =  [ 10,20,30, True]
l1

[10, 20, 30, True]

In [ ]:
np.array ([10,20,30,True])

array([10, 20, 30,  1])

In [ ]:
np.array ([10,20,30])

array([10, 20, 30])

In [ ]:
ar1 = np.array ([[10,20,30],[50,51,52]])
ar1

array([[10, 20, 30],
       [50, 51, 52]])

In [ ]:
ar1.ndim

2

In [ ]:
ar1.shape

(2, 3)

In [ ]:
list1 = [[10,20,30],[50,60,70]]
list1

[[10, 20, 30], [50, 60, 70]]

In [ ]:
np.array (list1 )

array([[10, 20, 30],
       [50, 60, 70]])

In [ ]:
ar1 = np.array ([[10,20,30],[50,51,52]])
ar1

array([[10, 20, 30],
       [50, 51, 52]])

In [ ]:
ar1 = np.array ([[10,20,30],[50,52]])
ar1

C:\Users\noble\AppData\Local\Temp\ipykernel_21596\1048052131.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar1 = np.array ([[10,20,30],[50,52]])


array([list([10, 20, 30]), list([50, 52])], dtype=object)

In [ ]:
ar1 = np.array ([[10,20,30],[50,0,52]])
ar1

array([[10, 20, 30],
       [50,  0, 52]])

In [ ]:
ar1 = np.array ([[10,20,30],[50,np.nan,52]])
ar1

array([[10., 20., 30.],
       [50., nan, 52.]])

In [ ]:
a1 = np.array ([10,20,30,40,50,60,45])
a1

array([10, 20, 30, 40, 50, 60, 45])

In [ ]:
a2 = a1[2:5]
a2

array([30, 40, 50])

In [ ]:
a2[1] = 444
a2

array([ 30, 444,  50])

In [ ]:
a1

array([ 10,  20,  30, 444,  50,  60,  45])

In [ ]:
a1 = np.array ([10,20,30,40,50,60,45])
a1

array([10, 20, 30, 40, 50, 60, 45])

In [ ]:
a2 = a1[2:5].copy()
a2

array([30, 40, 50])

In [ ]:
a2[1] = 444
a2

array([ 30, 444,  50])

In [ ]:
a1

array([10, 20, 30, 40, 50, 60, 45])

In [ ]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
a = np.arange(10,20)
a

array([10, 12, 14, 16, 18])

In [ ]:
a1 = np.array ([10,20,30,40,50,60,45])
a1

array([10, 20, 30, 40, 50, 60, 45])

In [ ]:
a2 = a1[2:5]
a2

array([30, 40, 50])

In [ ]:
a2[1] = 444
a2

array([ 30, 444,  50])

In [ ]:
a1

array([ 10,  20,  30, 444,  50,  60,  45])

In [ ]:
a1 = np.array ([10,20,30,40,50,60,45])
a1

array([10, 20, 30, 40, 50, 60, 45])

In [ ]:
a2 = a1[2:5]
a2

array([30, 40, 50])

In [ ]:
a2[1] = 444
a2

array([ 30, 444,  50])

In [ ]:
a1

array([ 10,  20,  30, 444,  50,  60,  45])

In [ ]:
a = np.arange (9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.arange (10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
a = np.arange (10,100,10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
a = np.arange (100,10, -10)
a

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:

import numpy as np
a = np.arange(9)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a.reshape (3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a.reshape (4,2)

ValueError: cannot reshape array of size 9 into shape (4,2)

In [ ]:
a = np.arange (30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
a.reshape (6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
a.reshape (3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
a.reshape (2,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
a.reshape (2,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
b = np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
b = np.ones((5,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
b *5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [ ]:
mat1 = np.arange (0,30)
mat1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
mat2 =np.reshape (mat1,(6,5),'F')
print (mat2)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [ ]:
mat2 =np.reshape (mat1,(6,5),'C')
print (mat2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [ ]:
mat2 =np.reshape (mat1,(6,5))
print (mat2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [ ]:
mat1.reshape (6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
mat2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
mat2.T

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [ ]:
a = np.arange (9)
b = a.reshape (3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a = np.arange (2,11)
c = a.reshape (3,3)
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
print (b)
print (c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
b+c

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
c-b

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
c*b

array([[ 0,  3,  8],
       [15, 24, 35],
       [48, 63, 80]])

In [ ]:
print (b)
print (c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
b@c

array([[ 21,  24,  27],
       [ 66,  78,  90],
       [111, 132, 153]])

In [ ]:
6+20+40

66

In [ ]:
b/c

array([[0.        , 0.33333333, 0.5       ],
       [0.6       , 0.66666667, 0.71428571],
       [0.75      , 0.77777778, 0.8       ]])

In [ ]:
b%c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
c%b

C:\Users\noble\AppData\Local\Temp\ipykernel_21596\1784681195.py:1: RuntimeWarning: divide by zero encountered in remainder
  c%b


array([[0, 0, 0],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
c//b

C:\Users\noble\AppData\Local\Temp\ipykernel_21596\3639078968.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  c//b


array([[0, 3, 2],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
print (mat2.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [ ]:
mat2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
vector = np.linspace(0,30,11)
print (vector)


[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30.]


In [ ]:
vector = np.linspace(20,40,7)
print (vector)

[20.         23.33333333 26.66666667 30.         33.33333333 36.66666667
 40.        ]


In [ ]:
EU_Sales = [1002, 4523,4123,3584]
APAC_Sales = [7854,9654,4582,8543]
US_Sales = [7845,4512,3652,7452]


In [ ]:
Sales = np.array ([EU_Sales, APAC_Sales,US_Sales])
print (Sales)


[[1002 4523 4123 3584]
 [7854 9654 4582 8543]
 [7845 4512 3652 7452]]


In [ ]:
Sales[1][2]

4582

In [ ]:
r= {'EU':0,'APAC':1,'US':2}
q={'Q1':0,'Q2':1,'Q3':2,'Q4':3}


In [ ]:
r['APAC']

1

In [ ]:
Sales[r['APAC']][q['Q3']]

4582

In [ ]:
Sales

array([[1002, 4523, 4123, 3584],
       [7854, 9654, 4582, 8543],
       [7845, 4512, 3652, 7452]])

In [ ]:
Sales[r['EU']][q['Q2']]

4523